# Podman Compose for RHOAI Ops Buddy - Production
#
# Uses pre-built images from quay.io/ops-buddy.
# In production mode, chat-ui uses API passthrough (browser -> chat-ui/api -> langgraph).
#
# Usage:
#   1. Copy config/prod.env.template to config/prod.env and fill in your values
#   2. Run: make prod-up (or: podman-compose -f compose.prod.yml --env-file config/prod.env up)
#   3. Access Chat UI at: http://localhost:3000
#   4. LangGraph API at: http://localhost:8000
#
version: '3.8'

services:
  # PostgreSQL for LangGraph state persistence
  postgres:
    image: docker.io/postgres:16-alpine
    environment:
      POSTGRES_DB: langgraph
      POSTGRES_USER: langgraph
      POSTGRES_PASSWORD: langgraph
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langgraph"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for LangGraph task queue
  redis:
    image: docker.io/redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data:z
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Cluster Monitor MCP Server
  cluster-monitor:
    image: quay.io/ops-buddy/rhoai-cluster-monitor-mcp:latest
    pull_policy: always
    ports:
      - "8001:8000"
    environment:
      HIVE_KUBECONFIG: /root/.kube/hive.yaml
      HIVE_CONTEXT: ${HIVE_CONTEXT:-hive-cluster}
      AWS_PROFILE: ${AWS_PROFILE:-rhoai}
      HOME: /root
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    volumes:
      - ${HIVE_KUBECONFIG_HOST}:/root/.kube/hive.yaml:ro,z
      - ${AWS_CREDENTIALS_HOST:-${HOME}/.aws/credentials}:/root/.aws/credentials:ro,z
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sleep 2"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  # Jenkins MCP Server
  jenkins-mcp:
    image: quay.io/ops-buddy/rhoai-jenkins-mcp:latest
    pull_policy: always
    ports:
      - "8002:8000"
    environment:
      JENKINS_URL: ${JENKINS_URL}
      JENKINS_USER: ${JENKINS_USER}
      JENKINS_PASSWORD: ${JENKINS_PASSWORD}
      JENKINS_SSL_VERIFY: ${JENKINS_SSL_VERIFY:-true}
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sleep 2"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  # Slack MCP Server
  slack-mcp:
    image: mirror-registry.osp.rh-ods.com:8443/admin/slack-ops:latest
    pull_policy: always
    ports:
      - "8003:8000"
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sleep 2"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  # LangGraph server for the agents
  langgraph-server:
    image: quay.io/ops-buddy/rhoai-ops-graph:latest
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: postgresql://langgraph:langgraph@postgres:5432/langgraph
      REDIS_URI: redis://redis:6379
      LLM_BASE_URL: ${LLM_BASE_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL}
      LLM_TEMPERATURE: ${LLM_TEMPERATURE:-0.7}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY:-}
      MCP_CONFIG_PATH: /app/config/mcp_servers.json
    volumes:
      - ./mcp_servers.json:/app/config/mcp_servers.json:ro,z
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      cluster-monitor:
        condition: service_healthy
      jenkins-mcp:
        condition: service_healthy
      slack-mcp:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/ok')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Agent Chat UI - Production mode (API passthrough)
  # The image is built with NEXT_PUBLIC_API_URL=/api for API passthrough
  # Browser -> chat-ui /api/* -> langgraph-server
  agent-chat-ui:
    image: quay.io/ops-buddy/chat-ui:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      # API passthrough: chat-ui proxies /api requests to langgraph-server
      # Default to internal service name; override in prod.env if chat-ui runs externally
      LANGGRAPH_API_URL: ${LANGGRAPH_API_URL:-http://langgraph-server:8000}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY:-}
    depends_on:
      langgraph-server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: rhoai-ops-buddy-network
