# Podman Compose for RHOAI Ops Buddy - Production
#
# Uses pre-built images from quay.io/ops-buddy
#
# Usage:
#   1. Ensure config.env is filled with your values
#   2. Run: podman-compose -f compose.prod.yml --env-file config.env up
#   3. Access Chat UI at: http://localhost:3000
#   4. LangGraph API at: http://localhost:8000
#
version: '3.8'

services:
  # PostgreSQL for LangGraph state persistence
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: langgraph
      POSTGRES_USER: langgraph
      POSTGRES_PASSWORD: langgraph
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langgraph"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for LangGraph task queue
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data:z
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Cluster Monitor MCP Server
  cluster-monitor:
    image: quay.io/ops-buddy/rhoai-cluster-monitor-mcp:latest
    ports:
      - "8001:8000"
    environment:
      HIVE_KUBECONFIG: /root/.kube/hive.yaml
      HIVE_CONTEXT: ${HIVE_CONTEXT:-hive-cluster}
      AWS_PROFILE: rhoai
      HOME: /root
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    volumes:
      - ${HIVE_KUBECONFIG_HOST}:/root/.kube/hive.yaml:ro,z
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro,z
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sleep 2"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  # Jenkins MCP Server
  jenkins-mcp:
    image: quay.io/ops-buddy/rhoai-jenkins-mcp:latest
    ports:
      - "8002:8000"
    environment:
      JENKINS_URL: ${JENKINS_URL}
      JENKINS_USER: ${JENKINS_USER}
      JENKINS_PASSWORD: ${JENKINS_PASSWORD}
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sleep 2"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  # LangGraph server for the agents
  langgraph-server:
    image: quay.io/ops-buddy/rhoai-ops-graph:latest
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.containers.internal:host-gateway"
    environment:
      DATABASE_URI: postgresql://langgraph:langgraph@postgres:5432/langgraph
      REDIS_URI: redis://redis:6379
      LLM_BASE_URL: ${LLM_BASE_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL}
      LLM_TEMPERATURE: ${LLM_TEMPERATURE:-0.7}
      LANGGRAPH_API_URL: ${LANGGRAPH_API_URL:-http://localhost:8000}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      cluster-monitor:
        condition: service_healthy
      jenkins-mcp:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/ok')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Agent Chat UI
  agent-chat-ui:
    image: quay.io/ops-buddy/chat-ui:latest
    ports:
      - "3000:3000"
    environment:
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGGRAPH_API_URL=http://langgraph-server:8000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_ASSISTANT_ID=agent
    depends_on:
      langgraph-server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: rhoai-ops-buddy-network
